volumes:
  prod-db-data: {}
  deno-cache: {}

services:
  # --- Production services (activate with --profile prod) ---
  api:
    profiles:
      - prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
      target: api
    ports:
      - "8000:8000"
    volumes:
      - prod-db-data:/app/api/data
    env_file:
      - .env
    environment:
      DATABASE_URL: file:./data/sqlite.db

  bot:
    profiles:
      - prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
      target: bot
    depends_on:
      - api
    env_file:
      - .env
    environment:
      API_URL: http://api:8000

  # --- Development service (activate with --profile dev) ---
  dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: tail -f /dev/null
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - deno-cache:/deno-dir
    env_file:
      - .env.dev

  # --- Tools service (activate with --profile tools) ---
  db-tools:
    profiles:
      - tools
    image: alpine:latest
    volumes:
      - prod-db-data:/prod-data
      - ./data:/data
